baseURL: "https://jayapalvummadi.org/hugo-website/" 
title: Jayapal Reddy Vummadi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 5 
        - name: Awards
          url: awards/
          weight: 2
        - name: Membership
          url: membership/
          weight: 3
        - name: Papers
          url: papers/
          weight: 4 
        - name: LinkedIn
          url: https://www.linkedin.com/in/jayapal-vummadi/
          weight: 6

params:
    description: "IT - Logistics | Supply chain Managment @ ZF Group | IEEE Senior Member | Esteemed Judge | Award-Winning Mentor | Speaker | Forbes Technology council Member | Globee Award Winner | GR Award | Global Leader Award"
    author: Jayapal Reddy Vummadi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","awards","membership","papers","linkedin"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          center: true
          title: Jayapal Reddy Vummadi
          subtitle: "IT - Logistics | Supply chain Managment @ ZF Group | IEEE Senior Member | Esteemed Judge | Award-Winning Mentor | Speaker | Forbes Technology council Member | Globee Award Winner | GR Award | Global Leader Award"
          imageUrl: "jayapalPicture.png"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: About
              url: about/
            - name: Awards
              url: awards/
            - name: Membership
              url: membership/
            - name: Papers
              url: papers/
            - name: LinkedIn
              url: https://www.linkedin.com/in/jayapal-vummadi/
 
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2